connection: &connection
  adapter: postgresql
  host: your host
  username: your username
  password: your password
  pool: 5
  timeout: 5000
  min_messages: warning

development:
  <<: *connection
  database: sitemap_generator

test: &test
  <<: *connection
  database: sitemap_generator_test

production:
  <<: *connection
  database: sitemap_generator
