connection: &connection
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  min_messages: warning

development:
  <<: *connection
  database: sitemap_generator

test: &test
  <<: *connection
  database: sitemap_generator_test

production:
  <<: *connection
  database: sitemap_generator
