connection: &connection
  adapter: postgresql
  username: your username
  password: your password
  pool: 5
  timeout: 5000

development:
  <<: *connection
  host: localhost
  database: sitemap_generator_development

test:
  <<: *connection
  host: localhost
  database: sitemap_generator_test

production:
  <<: *connection
  host: your_host
  database: sitemap_generator_production
